#!/usr/bin/env python3
"""Generate engine/src/searchless_vocab.rs from searchless_chess_vocabulary.json.

One-time codegen. The output is a committed Rust source file with const arrays
describing the searchless_chess 1968-action vocabulary (UCI strings and
factored src/dst/promo decompositions).

Usage:
    uv run python scripts/generate_searchless_vocab.py
"""

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VOCAB_JSON = REPO_ROOT / "searchless_chess_vocabulary.json"
OUTPUT_RS = REPO_ROOT / "engine" / "src" / "searchless_vocab.rs"

# PAWN's square indexing: file-major within rank.
# a1=0, b1=1, ..., h1=7, a2=8, ..., h8=63
SQUARE_NAMES = [f"{f}{r}" for r in "12345678" for f in "abcdefgh"]
assert len(SQUARE_NAMES) == 64

PROMO_MAP = {"q": 1, "r": 2, "b": 3, "n": 4}


def main() -> None:
    with open(VOCAB_JSON) as f:
        vocab = json.load(f)

    action_to_move = vocab["action_to_move"]
    n_actions = len(action_to_move)
    assert n_actions == 1968, f"Expected 1968 actions, got {n_actions}"

    uci_strs: list[str] = []
    src_arr: list[int] = []
    dst_arr: list[int] = []
    promo_arr: list[int] = []

    for action_idx in range(n_actions):
        uci = action_to_move[str(action_idx)]
        uci_strs.append(uci)

        src_name = uci[:2]
        dst_name = uci[2:4]
        promo_suffix = uci[4:] if len(uci) > 4 else ""

        src_arr.append(SQUARE_NAMES.index(src_name))
        dst_arr.append(SQUARE_NAMES.index(dst_name))
        promo_arr.append(PROMO_MAP.get(promo_suffix, 0))

    lines: list[str] = []
    lines.append("//! Auto-generated by scripts/generate_searchless_vocab.py — do not edit.")
    lines.append("//!")
    lines.append("//! Lookup tables for the searchless_chess 1968-action vocabulary.")
    lines.append("//! Actions 0–1967 are 1:1 with DeepMind's searchless_chess vocabulary.")
    lines.append("")
    lines.append(f"pub const NUM_ACTIONS: usize = {n_actions};")
    lines.append("")

    lines.append(f"pub const ACTION_TO_UCI: [&str; {n_actions}] = [")
    for uci in uci_strs:
        lines.append(f'    "{uci}",')
    lines.append("];")
    lines.append("")

    lines.append("/// Source square index (file-major: a1=0, b1=1, ..., h8=63).")
    lines.append(f"pub const ACTION_TO_SRC: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 16):
        chunk = src_arr[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:2}" for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    lines.append("/// Destination square index (file-major: a1=0, b1=1, ..., h8=63).")
    lines.append(f"pub const ACTION_TO_DST: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 16):
        chunk = dst_arr[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:2}" for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    lines.append("/// Promotion type: 0=none, 1=queen, 2=rook, 3=bishop, 4=knight.")
    lines.append(f"pub const ACTION_TO_PROMO: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 32):
        chunk = promo_arr[chunk_start:chunk_start + 32]
        lines.append("    " + ", ".join(str(x) for x in chunk) + ",")
    lines.append("];")

    content = "\n".join(lines) + "\n"

    OUTPUT_RS.write_text(content)
    print(f"Generated {OUTPUT_RS} ({n_actions} actions, {len(content)} bytes)")


if __name__ == "__main__":
    main()
