#!/usr/bin/env python3
"""Generate engine/src/searchless_vocab.rs from searchless_chess_vocabulary.json.

One-time codegen. The output is a committed Rust source file with const arrays
mapping between the searchless_chess 1968-action vocabulary and PAWN's legacy
4272-token vocabulary.

Usage:
    uv run python scripts/generate_searchless_vocab.py
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VOCAB_JSON = REPO_ROOT / "searchless_chess_vocabulary.json"
OUTPUT_RS = REPO_ROOT / "engine" / "src" / "searchless_vocab.rs"

# PAWN's square indexing: file-major within rank.
# a1=0, b1=1, ..., h1=7, a2=8, ..., h8=63
SQUARE_NAMES = [
    f"{f}{r}" for r in "12345678" for f in "abcdefgh"
]
assert len(SQUARE_NAMES) == 64

PROMO_MAP = {"q": 1, "r": 2, "b": 3, "n": 4}

# Legacy PAWN promotion pairs (same order as engine/src/vocab.rs PROMO_PAIRS_ARRAY)
def _legacy_promo_pairs() -> list[tuple[int, int]]:
    pairs: list[tuple[int, int]] = []
    # White straight
    for f in range(8):
        pairs.append((6 * 8 + f, 7 * 8 + f))
    # White left-capture
    for f in range(1, 8):
        pairs.append((6 * 8 + f, 7 * 8 + f - 1))
    # White right-capture
    for f in range(7):
        pairs.append((6 * 8 + f, 7 * 8 + f + 1))
    # Black straight
    for f in range(8):
        pairs.append((1 * 8 + f, 0 * 8 + f))
    # Black left-capture
    for f in range(1, 8):
        pairs.append((1 * 8 + f, 0 * 8 + f - 1))
    # Black right-capture
    for f in range(7):
        pairs.append((1 * 8 + f, 0 * 8 + f + 1))
    assert len(pairs) == 44
    return pairs


LEGACY_PROMO_PAIRS = _legacy_promo_pairs()
LEGACY_PROMO_PAIR_INDEX = {p: i for i, p in enumerate(LEGACY_PROMO_PAIRS)}


def uci_to_legacy_pawn_token(uci: str) -> int:
    """Convert a UCI move string to PAWN's legacy token ID."""
    src_name = uci[:2]
    dst_name = uci[2:4]
    promo_suffix = uci[4:] if len(uci) > 4 else ""

    src = SQUARE_NAMES.index(src_name)
    dst = SQUARE_NAMES.index(dst_name)

    if promo_suffix:
        # Promotion: legacy token = 4097 + pair_idx * 4 + promo_type
        # promo_type for legacy: q=0, r=1, b=2, n=3
        pair_idx = LEGACY_PROMO_PAIR_INDEX[(src, dst)]
        promo_type = {"q": 0, "r": 1, "b": 2, "n": 3}[promo_suffix]
        return 4097 + pair_idx * 4 + promo_type
    else:
        # Base grid: legacy token = src * 64 + dst + 1
        return src * 64 + dst + 1


def main() -> None:
    with open(VOCAB_JSON) as f:
        vocab = json.load(f)

    action_to_move = vocab["action_to_move"]
    move_to_action = vocab["move_to_action"]

    n_actions = len(action_to_move)
    assert n_actions == 1968, f"Expected 1968 actions, got {n_actions}"

    # Build arrays indexed by action ID (0..1967)
    uci_strs: list[str] = []
    src_arr: list[int] = []
    dst_arr: list[int] = []
    promo_arr: list[int] = []
    searchless_to_pawn: list[int] = []

    for action_idx in range(n_actions):
        uci = action_to_move[str(action_idx)]
        uci_strs.append(uci)

        src_name = uci[:2]
        dst_name = uci[2:4]
        promo_suffix = uci[4:] if len(uci) > 4 else ""

        src = SQUARE_NAMES.index(src_name)
        dst = SQUARE_NAMES.index(dst_name)
        promo = PROMO_MAP.get(promo_suffix, 0)

        src_arr.append(src)
        dst_arr.append(dst)
        promo_arr.append(promo)
        searchless_to_pawn.append(uci_to_legacy_pawn_token(uci))

    # Build PAWN_TO_SEARCHLESS: legacy token 0..4272 -> searchless action or -1
    # Legacy tokens: 1..4096 (base grid), 4097..4272 (promotions)
    # Token 0 is legacy PAD — map to -1
    pawn_to_searchless = [-1] * 4273  # indices 0..4272
    for action_idx, pawn_token in enumerate(searchless_to_pawn):
        pawn_to_searchless[pawn_token] = action_idx

    # Verify roundtrip
    for action_idx in range(n_actions):
        pawn_token = searchless_to_pawn[action_idx]
        assert pawn_to_searchless[pawn_token] == action_idx, \
            f"Roundtrip failed: action {action_idx} -> pawn {pawn_token} -> {pawn_to_searchless[pawn_token]}"

    # Verify all searchless actions map to valid pawn tokens
    for action_idx in range(n_actions):
        pawn_token = searchless_to_pawn[action_idx]
        assert 1 <= pawn_token <= 4272, \
            f"Action {action_idx} maps to invalid pawn token {pawn_token}"

    # Count how many legacy tokens map to valid actions
    valid_legacy = sum(1 for x in pawn_to_searchless if x >= 0)
    assert valid_legacy == n_actions, \
        f"Expected {n_actions} valid legacy mappings, got {valid_legacy}"

    # Generate Rust source
    lines: list[str] = []
    lines.append("//! Auto-generated by scripts/generate_searchless_vocab.py — do not edit.")
    lines.append("//!")
    lines.append("//! Lookup tables for the searchless_chess 1968-action vocabulary.")
    lines.append("//! Actions 0–1967 are 1:1 with DeepMind's searchless_chess vocabulary.")
    lines.append("")
    lines.append(f"pub const NUM_ACTIONS: usize = {n_actions};")
    lines.append("")

    # ACTION_TO_UCI
    lines.append(f"pub const ACTION_TO_UCI: [&str; {n_actions}] = [")
    for i, uci in enumerate(uci_strs):
        comma = "," if i < n_actions - 1 else ","
        lines.append(f'    "{uci}"{comma}')
    lines.append("];")
    lines.append("")

    # ACTION_TO_SRC
    lines.append(f"/// Source square index (file-major: a1=0, b1=1, ..., h8=63).")
    lines.append(f"pub const ACTION_TO_SRC: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 16):
        chunk = src_arr[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:2}" for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    # ACTION_TO_DST
    lines.append(f"/// Destination square index (file-major: a1=0, b1=1, ..., h8=63).")
    lines.append(f"pub const ACTION_TO_DST: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 16):
        chunk = dst_arr[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:2}" for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    # ACTION_TO_PROMO
    lines.append("/// Promotion type: 0=none, 1=queen, 2=rook, 3=bishop, 4=knight.")
    lines.append(f"pub const ACTION_TO_PROMO: [u8; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 32):
        chunk = promo_arr[chunk_start:chunk_start + 32]
        lines.append("    " + ", ".join(str(x) for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    # PAWN_TO_SEARCHLESS
    lines.append("/// Legacy PAWN token (0..4272) → searchless action index, or -1 if impossible.")
    lines.append("/// Token 0 is legacy PAD. Tokens 1–4096 are the dense 64×64 grid.")
    lines.append("/// Tokens 4097–4272 are promotions (44 pairs × 4 types).")
    lines.append(f"pub const PAWN_TO_SEARCHLESS: [i16; {len(pawn_to_searchless)}] = [")
    for chunk_start in range(0, len(pawn_to_searchless), 16):
        chunk = pawn_to_searchless[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:5}" for x in chunk) + ",")
    lines.append("];")
    lines.append("")

    # SEARCHLESS_TO_PAWN
    lines.append("/// Searchless action (0..1967) → legacy PAWN token (1..4272).")
    lines.append(f"pub const SEARCHLESS_TO_PAWN: [u16; {n_actions}] = [")
    for chunk_start in range(0, n_actions, 16):
        chunk = searchless_to_pawn[chunk_start:chunk_start + 16]
        lines.append("    " + ", ".join(f"{x:4}" for x in chunk) + ",")
    lines.append("];")

    content = "\n".join(lines) + "\n"

    OUTPUT_RS.write_text(content)
    print(f"Generated {OUTPUT_RS} ({n_actions} actions, {len(content)} bytes)")
    print(f"  {valid_legacy} legacy tokens map to actions")
    print(f"  {len(pawn_to_searchless) - valid_legacy} legacy tokens are impossible moves (mapped to -1)")


if __name__ == "__main__":
    main()
